name: tests

on: [push]
jobs:
  Unit_Tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show Current Version of Xcode
      id: show-version
      run: xcodebuild -version
    - name: Install XCode
      id: install-xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    - name: Run unit tests
      id: unit-tests
      run: xcodebuild test -scheme iACC -project iACC.xcodeproj -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max' | xcpretty && exit ${PIPESTATUS[0]}
